In [4]:
from sklearn.datasets import load_digits, load_breast_cancer
from sklearn.cross_validation import cross_val_score
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [14]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

In [26]:
data_d = load_digits()
data_c = load_breast_cancer()

In [27]:
print(data_d.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [28]:
print(data_c.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [12]:
X = data_d.data
y = data_d.target
A = data_c.data
b = data_c.target

In [20]:
model_N = GaussianNB()
model_B = BernoulliNB()
model_M = MultinomialNB()

In [24]:
# Мультиномиальное распределение
model_M.fit(X, y)
ans_Md = cross_val_score(model_M, X, y)
print(ans_Md.mean())

model_M.fit(A, b)
ans_Mc = cross_val_score(model_M, A, b)
print(ans_Mc.mean())


0.8708771489735053
0.8945790401930752


In [23]:
#Нормальное распределение
model_N.fit(X, y)
ans_Nd = cross_val_score(model_N, X, y)
print(ans_Nd.mean() )

model_N.fit(A, b)
ans_Nc = cross_val_score(model_N, A, b)
print(ans_Nc.mean())

0.8186003803550138
0.9367492806089297


In [25]:
#Бернулли
model_B.fit(X, y)
ans_Bd = cross_val_score(model_B, X, y)
print(ans_Bd.mean() )

model_B.fit(A, b)
ans_Bc = cross_val_score(model_B, A, b)
print(ans_Bc.mean())

0.8258236507780582
0.6274204028589994


In [35]:
ANS2 = 0.8708771489735053
ANS1 = 0.9367492806089297
ANS3 = '3 4'

In [36]:
def write_answer1(ans1):
    with open("answer1.txt", "w") as fout:
        fout.write(str(ans1))
        
def write_answer2(ans2):
    with open("answer2.txt", "w") as fout:
        fout.write(str(ans2))
        
def write_answer3(ans3):
    with open("answer3.txt", "w") as fout:
        fout.write(str(ans3))

In [37]:
write_answer1(ANS1)
write_answer2(ANS2)
write_answer3(ANS3)